name: Build for MacOS, Ubuntu and Windows

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # os: [macos-11]
        os: [ubuntu-latest]
        # os: [macos-11, ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
            
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        # -r requirements-dev.txt

      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile pad.py

      - uses: actions/upload-artifact@v2
        with:
          name: pad.exe
          path: dist

  #     - name: Build Executable
  #       uses: Nuitka/Nuitka-Action@main
  #       with:
  #         # args: --macos-target-arch=arm64
  #         script-name: pad.py
  #         onefile: true
  
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ${{ runner.os }} Build
  #         path: |
  #           build/*.exe
  #           build/*.bin
  #           build/*.app/**/*
  # buildm1:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Check-out repository
  #       uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
  #         architecture: 'x64'
  #         cache: 'pip'
  #         cache-dependency-path: |
  #           **/requirements*.txt
            
  #     - name: Install Dependencies
  #       run: |
  #         pip install -r requirements.txt py2app
  #       # -r requirements-dev.txt
          
  #     - name: Build Executable
  #       run: |
  #         py2applet pad.py

  #     - name: Upload build artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: pad-macos-m1
  #         path: pad.app 